Vagrant.configure(2) do |config|
#  config.hostmanager.enabled = true

  config.vm.box = "bento/centos-6.7"

  config.vm.define "ansible local", primary: true do |h|
    h.vm.network "private_network", ip: "192.168.2.40"
  h.vm.box_download_insecure=true
#    h.vm.network "public_network", bridge: "wlo1"
    h.vm.hostname = 'Git'
  end

  config.vm.define "ansible client" do |h1|
  h1.vm.box = "bento/centos-6.7"
    h1.vm.network "private_network", ip: "192.168.2.41"
   h1.vm.box_download_insecure=true
#    h.vm.network "public_network", bridge: "wlo1"
    h1.vm.hostname = 'Jenkinsserver'
	h1.vm.provision "shell", inline: <<-SHELL
	sudo yum update
    sudo yum install -y epel-release
 #  sudo yum install -y httpd
	sudo yum install java-1.7.0-openjdk
	sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
    sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
    sudo yum install jenkins
	sudo service jenkins start/stop/restart
	sudo chkconfig jenkins on
   SHELL
  end

  config.vm.define "ansible server1" do |h2|
  h2.vm.box = "bento/centos-6.7"
    h2.vm.network "private_network", ip: "192.168.2.42"
  h2.vm.box_download_insecure=true
#    h.vm.network "public_network", bridge: "wlo1"
    h2.vm.hostname = 'nexusserver'
  end

  config.vm.define "ansible server2" do |h3|
  h3.vm.box = "ubuntu/trusty64"
    h3.vm.network "private_network", ip: "192.168.2.43"
  h3.vm.box_download_insecure=true
#    h.vm.network "public_network", bridge: "wlo1"
    h3.vm.hostname = 'Webserver1'
  end

  config.vm.define "web02" do |h4|
  h4.vm.box = "bento/centos-6.7"
  h4.vm.box_download_insecure=true
    h4.vm.network "private_network", ip: "192.168.2.39"
#    h.vm.network "public_network", bridge: "wlo1"
    h4.vm.hostname = 'Webserver2'
  end
end
